/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import static Ventanas.Imprimir_Personal02.jTableBD;
import com.placeholder.PlaceHolder;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author tesoreria
 */
public class Consulta_de_Saldos extends javax.swing.JFrame {
    //CONEXION A LA BASE DE DATOS
    Conectar cc= new Conectar();
    Connection cn= cc.conexion();
    
    //SEGUNDA CONEXION A LA BASE DE DATOS
    Conectar cc1= new Conectar();
    Connection cn1= cc1.conexion();
    
    public static String Legajos;

    /**
     * Creates new form Padron_de_Empleados
     */
    public Consulta_de_Saldos() {
        initComponents();
        this.setLocationRelativeTo(this);  //CENTRAR VENTANA
        //JPANEL INVISIBLE
        jPanel2.setVisible(false);
        //FIN JPANEL INVISIBLE        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBD = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();

        jMenuItem1.setText("MODIFICAR");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("ELIMINAR");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(910, 540));
        setMinimumSize(new java.awt.Dimension(910, 540));
        setPreferredSize(new java.awt.Dimension(910, 540));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("SALDOS POR LEGAJOS");
        jLabel2.setMaximumSize(new java.awt.Dimension(700, 60));
        jLabel2.setMinimumSize(new java.awt.Dimension(700, 60));
        jLabel2.setPreferredSize(new java.awt.Dimension(700, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/franja azul.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(600, 60));
        jLabel1.setMinimumSize(new java.awt.Dimension(600, 60));
        jLabel1.setPreferredSize(new java.awt.Dimension(600, 60));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton_volver_50x50.png"))); // NOI18N
        jButton1.setToolTipText("VOLVER AL MENU PRINCIPAL");
        jButton1.setMaximumSize(new java.awt.Dimension(60, 60));
        jButton1.setMinimumSize(new java.awt.Dimension(60, 60));
        jButton1.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMaximumSize(new java.awt.Dimension(165, 340));
        jPanel1.setMinimumSize(new java.awt.Dimension(165, 340));
        jPanel1.setPreferredSize(new java.awt.Dimension(165, 340));

        jLabel3.setText("Fecha Inicial:");

        jLabel4.setText("Fecha Final:");

        jLabel5.setText("Legajo:");

        jLabel6.setText("Apellido:");

        jLabel7.setText("Nombre/s:");

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setEnabled(false);

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setEnabled(false);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton_buscar_30x30.png"))); // NOI18N
        jButton2.setToolTipText("BUSCAR POR LEG, DNI O APELLIDO");
        jButton2.setMaximumSize(new java.awt.Dimension(30, 30));
        jButton2.setMinimumSize(new java.awt.Dimension(30, 30));
        jButton2.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton_imprimir_30x30.png"))); // NOI18N
        jButton3.setEnabled(false);
        jButton3.setMaximumSize(new java.awt.Dimension(30, 30));
        jButton3.setMinimumSize(new java.awt.Dimension(30, 30));
        jButton3.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel5)))
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTableBD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableBD.setComponentPopupMenu(jPopupMenu1);
        jTableBD.setMinimumSize(new java.awt.Dimension(60, 400));
        jScrollPane1.setViewportView(jTableBD);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0)));
        jPanel2.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("SALDOS AL DIA");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("jLabel9");

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextField4)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(227, 227, 227)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(281, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(200, 200, 200)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 447, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Interfaz interfaz = new Interfaz();
        interfaz.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //INICIO - PARA COMPLETAR LOS 3 DIGITOS DEL CAMPO LEG
        if (!(jTextField1.getText().equals(""))){
            jTextField1.setText(String.format("%03d",(Integer.parseInt(jTextField1.getText().trim()))));
        }
        //FIN - PARA COMPLETAR LOS 3 DIGITOS DEL CAMPO LEG
        //INICIO - COMPARAR FECHA INICIAL SEA MENOR O IGUAL, A FECHA FINAL
        if (jDateChooser1.getDate().after(jDateChooser2.getDate())){
            JOptionPane.showMessageDialog(null, "FECHA INICIAL, debe ser menor o igual que, FECHA FINAL", "ERROR", JOptionPane.WARNING_MESSAGE);
            //INHABILITAR EL BOTON IMPRIMIR
            jButton3.setEnabled(false);
        }
        //FIN - COMPARAR DESDE LEG SEA MENOR O IGUAL, A HASTA LEG
        //INICIO - SI jTextField1 ESTA VACIO, BORRA EL jTextField2 Y EL jTextField3. Y sino busca al empleado
        if (jTextField1.getText().length() == 0){
            jTextField2.setText("");
            jTextField3.setText("");
        }else{
            String sql = "SELECT * FROM `empleados` WHERE `Leg` LIKE '%"+jTextField1.getText()+"%'";
            String datos[] = new String [2];
            Statement st;
            try{
                st= cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()){
                    jTextField2.setText(rs.getString(4));
                    jTextField3.setText(rs.getString(5));
                    }
            }catch (SQLException ex){
                Logger.getLogger(Padron_de_Empleados.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        //FIN - SI jTextField1 ESTA VACIO, BORRA EL jTextField2 Y EL jTextField3. Y sino busca al empleado
        //INICIO - CUANDO SE LLENO CORRECTAMENTE LOS CAMPOS, SE PROCEDE A BUSCAR
        if(jDateChooser1.getDate().before(jDateChooser2.getDate())){
            int activo = 0;
            //INICIO - AL REALIZAR LA BUSQUEDA, SE GUARDA LOS CAMPOS NECESARIOS PARA LUEGO IMPRIMIR
            Interfaz.Fecha_Inicial=jDateChooser1.getDate();
            Interfaz.Fecha_Final=jDateChooser2.getDate();
            Interfaz.Leg=jTextField1.getText();
            Interfaz.Apellido=jTextField2.getText();
            Interfaz.Nombre=jTextField3.getText();
            //FIN - AL REALIZAR LA BUSQUEDA, SE GUARDA LOS CAMPOS NECESARIOS PARA LUEGO IMPRIMIR
            if (jTextField1.getText().length() == 0){
                // DecimalFormatSymbols separadoresPersonalizados = new DecimalFormatSymbols();
                //separadoresPersonalizados.setDecimalSeparator('.');
                DecimalFormat formato1 = new DecimalFormat("###,###");
                //JPANEL INVISIBLE
                jPanel2.setVisible(false);
                DefaultTableModel modelo = new DefaultTableModel();
                //PODER ORDENAR DE MAYOR A MENOR O VICEVERSA
                TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<>(modelo);
                jTableBD.setRowSorter(elQueOrdena);
                //FIN
                //CAMBIAR FORMATO DEL JDATECHOOSER PARA SUBIR AL SQL
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                modelo.addColumn("Legajos");
                modelo.addColumn("Apellido");
                modelo.addColumn("Nombre");
                modelo.addColumn("Netos");
                jTableBD.setModel(modelo);
                //PONER TAMAÑO DE LAS COLUMNAS
                jTableBD.getColumn("Legajos").setPreferredWidth(20);
                jTableBD.getColumn("Apellido").setPreferredWidth(70);
                jTableBD.getColumn("Nombre").setPreferredWidth(100);
                jTableBD.getColumn("Netos").setPreferredWidth(330);
                //BUSCAR DATOS EN TABLA COMPLETA
                String sql = "SELECT Leg as Legajos, sum(`ImporteN`+`ImporteP`) as Netos FROM `saldos` WHERE `Fecha` BETWEEN '2020-01-01' AND '"+sdf.format(jDateChooser2.getDate())+"' group by Leg";
                String datos[] = new String [4];
                Statement st;
                try{
                    st= cn.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                    while (rs.next()){
                        //BUSCAR EL DNI EN LA SEGUNDA TABLA (EMPLEADOS)
                        String sql1 = "SELECT * FROM `empleados` WHERE `Leg` LIKE '%"+rs.getString(1)+"%'";
                        Statement st1;
                        try{
                            st1= cn1.createStatement();
                            ResultSet rs1 = st1.executeQuery(sql1);
                            while (rs1.next()){
                                datos[1]=rs1.getString(4);
                                datos[2]=rs1.getString(5);
                                //INICIO - PARA VERIFICAR SI EL LEGAJO ESTA DADO DE BAJA
                                if (rs1.getString(9).equals("S")){
                                    activo=1;
                                }
                                if (rs1.getString(9).equals("N")){
                                    activo=0;
                                }
                                //FIN - PARA VERIFICAR SI EL LEGAJO ESTA DADO DE BAJA
                            }
                        }catch (SQLException ex){
                            Logger.getLogger(Padron_de_Empleados.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        //FINALIZA LA BUSQUEDA DE LA SEGUNDA TABLA
                        datos[0]=rs.getString(1);
                        //datos[3]="$ "+formato1.format(Integer.parseInt(rs.getString(2))).replace('.', ',');
                        datos[3]="$ "+String.format("%.2f",Double.parseDouble(rs.getString(2))).replace(',', '.');
                        //datos[3]=Double.parseDouble(rs.getString(2));
                        //datos[3]=datos[3].substring(0, 4);
                        //datos[8]="$ "+String.format("%.2f",saldo).replace(',', '.');
                        //INICIO - PARA NO CARGAR EN LA TABLA LOS LEGAJOS DADOS DE BAJA
                        if (activo==1){
                            modelo.addRow(datos);
                        }
                        //FIN - PARA NO CARGAR EN LA TABLA LOS LEGAJOS DADOS DE BAJA
                    }
                    jTableBD.setModel(modelo);
                    //PARA COLOCAR LAS FILAS CON VALORES NEGATIVOS EN COLOR ROJO
                    jTableBD.setDefaultRenderer (Object.class, new FormatoTabla());
                }catch (SQLException ex){
                    Logger.getLogger(Padron_de_Empleados.class.getName()).log(Level.SEVERE, null, ex);
                }
                //INHABILITAR EL BOTON IMPRIMIR
                jButton3.setEnabled(false);
            }else{
                //PARA PONER DOS DIGITOS A LOS DECIMALES
                DecimalFormatSymbols separadoresPersonalizados = new DecimalFormatSymbols();
                separadoresPersonalizados.setDecimalSeparator('.');
                DecimalFormat formato1 = new DecimalFormat("#.##");
                double bandera1=0.0;
                int bandera2=0;
                double saldo=0.0;
                DefaultTableModel modelo = new DefaultTableModel();
                //PODER ORDENAR DE MAYOR A MENOR O VICEVERSA
                TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<>(modelo);
                jTableBD.setRowSorter(elQueOrdena);
                //FIN
                //CAMBIAR FORMATO DEL JDATECHOOSER PARA SUBIR AL SQL
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                SimpleDateFormat sdf1 = new SimpleDateFormat("dd/MM/yyyy");
                modelo.addColumn("COD");
                modelo.addColumn("FECHA");
                modelo.addColumn("CONCEPTO");
                modelo.addColumn("N° VALE");
                modelo.addColumn("MES");
                modelo.addColumn("AÑO");
                modelo.addColumn("IMPORTE (-)");
                modelo.addColumn("IMPORTE (+)");
                modelo.addColumn("SALDO");
                jTableBD.setModel(modelo);
                //PONER TAMAÑO DE LAS COLUMNAS
                jTableBD.getColumn("COD").setPreferredWidth(01);
                jTableBD.getColumn("FECHA").setPreferredWidth(90);
                jTableBD.getColumn("CONCEPTO").setPreferredWidth(200);
                jTableBD.getColumn("N° VALE").setPreferredWidth(90);
                jTableBD.getColumn("MES").setPreferredWidth(70);
                jTableBD.getColumn("AÑO").setPreferredWidth(70);
                jTableBD.getColumn("IMPORTE (-)").setPreferredWidth(75);
                jTableBD.getColumn("IMPORTE (+)").setPreferredWidth(75);
                jTableBD.getColumn("SALDO").setPreferredWidth(90);
                //FIN - PONER TAMAÑO DE LAS COLUMNAS
                //INICIO - ALINEAR LAS COLUMNAS A LA DERECHA
                DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
                tcr.setHorizontalAlignment(SwingConstants.RIGHT);
                jTableBD.getColumnModel().getColumn(8).setCellRenderer(tcr);
                //FIN - ALINEAR LAS COLUMNAS A LA DERECHA
                //INICIO - ALINEAR LAS COLUMNAS AL CENTRO
                DefaultTableCellRenderer tcr1 = new DefaultTableCellRenderer();
                tcr1.setHorizontalAlignment(SwingConstants.CENTER);
                jTableBD.getColumnModel().getColumn(6).setCellRenderer(tcr1);
                jTableBD.getColumnModel().getColumn(7).setCellRenderer(tcr1);
                //FIN - ALINEAR LAS COLUMNAS AL CENTRO
                //BUSCAR DATOS EN TABLA COMPLETA
                String sql = "SELECT * FROM `saldos` WHERE `Leg` LIKE '%"+jTextField1.getText()+"%' ORDER BY `Fecha` ASC";
                String datos[] = new String [9];
                String bandera3[] = new String [9];
                Statement st;
                try{
                    st= cn.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                    while (rs.next()){
                        bandera1= saldo;
                        datos[0]=rs.getString(1);
                        datos[1]=rs.getString(3);
                        datos[2]=rs.getString(4);
                        datos[3]=rs.getString(5);
                        datos[4]=rs.getString(6);
                        datos[5]=rs.getString(7);
                        datos[6]=rs.getString(8);
                        datos[7]=rs.getString(9);
                        if (rs.getString(8).equals("0")){
                            saldo= saldo+Double.parseDouble(rs.getString(9));
                        } else{
                            saldo= saldo+Double.parseDouble(rs.getString(8));
                        }
                        datos[8]="$ "+String.format("%.2f",saldo).replace(',', '.');
                        //modelo.addRow(datos);
                        //PARA COMPARAR FECHAS
                        Date fechainicio= jDateChooser1.getDate();
                        Date fechafin= jDateChooser2.getDate();
                        // Comparo las fechas y despliego el resultado
                        switch (fechainicio.compareTo(rs.getDate(3))){
                            case 0:
                                switch (fechafin.compareTo(rs.getDate(3))){
                                    case 1:
                                        bandera2=bandera2+1;
                                        if (bandera2==1){
                                            bandera3[2]="SALDO ANTERIOR";
                                            bandera3[8]="$ "+String.format("%.2f",bandera1).replace(',', '.');
                                            modelo.addRow(bandera3);
                                        }
                                        modelo.addRow(datos);
                                        break;
                                    case 0:
                                        bandera2=bandera2+1;
                                        if (bandera2==1){
                                            bandera3[2]="SALDO ANTERIOR";
                                            bandera3[8]="$ "+String.format("%.2f",bandera1).replace(',', '.');
                                            modelo.addRow(bandera3);
                                        }
                                        modelo.addRow(datos);
                                        break;
                                }
                                break;
                            case -1:
                                switch (fechafin.compareTo(rs.getDate(3))){
                                    case 1:
                                        bandera2=bandera2+1;
                                        if (bandera2==1){
                                            bandera3[2]="SALDO ANTERIOR";
                                            bandera3[8]="$ "+String.format("%.2f",bandera1).replace(',', '.');
                                            modelo.addRow(bandera3);
                                        }
                                        modelo.addRow(datos);
                                        break;
                                    case 0:
                                        bandera2=bandera2+1;
                                        if (bandera2==1){
                                            bandera3[2]="SALDO ANTERIOR";
                                            bandera3[8]="$ "+String.format("%.2f",bandera1).replace(',', '.');
                                            modelo.addRow(bandera3);
                                        }
                                        modelo.addRow(datos);
                                        break;
                                }
                                break;
                        }
                    }
                    jTableBD.setModel(modelo);
                }catch (SQLException ex){
                    Logger.getLogger(Padron_de_Empleados.class.getName()).log(Level.SEVERE, null, ex);
                }
                //SUMAR ARRASTRE DE TODOS LOS SALDOS HASTA CIERTA FECHA XX
                sql = "SELECT sum(`ImporteN`+`ImporteP`) FROM `saldos` WHERE `Leg` LIKE '%"+jTextField1.getText()+"%' AND `Fecha` BETWEEN '2019-12-01' AND '"+sdf.format(jDateChooser2.getDate())+"' ORDER BY `Leg` ASC";
                Statement st1;
                try{
                    st1= cn.createStatement();
                    ResultSet rs1 = st1.executeQuery(sql);
                    while (rs1.next()){
                        jTextField4.setText("$ "+String.format("%.2f",Double.parseDouble(rs1.getString(1))).replace(',', '.'));
                    }
                }catch (SQLException ex){
                    Logger.getLogger(Padron_de_Empleados.class.getName()).log(Level.SEVERE, null, ex);
                }
                //PONER LA FECHA FINAL EN EL JLABEL
                jLabel9.setText(sdf1.format(jDateChooser2.getDate()));
                //PONER EN MODO VISIBLE EL JPANEL2
                jPanel2.setVisible(true);
                //HABILITAR EL BOTON IMPRIMIR
                jButton3.setEnabled(true);
            }
        }
        //FIN - CUANDO SE LLENO CORRECTAMENTE LOS CAMPOS, SE PROCEDE A BUSCAR
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        //SI jTextField1 ESTA VACIO, BORRA EL jTextField2 Y EL jTextField3. Y sino busca al empleado, e inhabilita el boton imprimir
        if (jTextField1.getText().length() == 0){
            jTextField2.setText("");
            jTextField3.setText("");
            jButton3.setEnabled(false);
        }else{
            String sql = "SELECT * FROM `empleados` WHERE `Leg` LIKE '%"+jTextField1.getText()+"%'";
            
            String datos[] = new String [2];
            Statement st;
            
            try{
                st= cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()){
                    jTextField2.setText(rs.getString(4));
                    jTextField3.setText(rs.getString(5));
                    }
                }catch (SQLException ex){
                    Logger.getLogger(Padron_de_Empleados.class.getName()).log(Level.SEVERE, null, ex);
                    }
            }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        //PERMITE EL INGRESO UNICAMENTE DE 3 DIGITOS
        if (jTextField1.getText().length()== 3){
            evt.consume();
        } 
        //Permitir solo el ingreso de NUMEROS
        char car = evt.getKeyChar();
        if(car<'0' || car>'9') evt.consume();
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        //SI jTextField1 ESTA VACIO, BORRA EL jTextField2 Y EL jTextField3, e inhabilita el boton imprimir
        if (jTextField1.getText().length() == 0){
            jTextField2.setText("");
            jTextField3.setText("");
            jButton3.setEnabled(false);
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //CAMBIAR FORMATO DEL JDATECHOOSER PARA SUBIR AL SQL
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat sdf1 = new SimpleDateFormat("dd/MM/yyyy");
        
        Imprimir_Personal02 a = new Imprimir_Personal02();
        a.setVisible(true);
        this.setVisible(false);
        
        Interfaz.Fecha_Inicial=jDateChooser1.getDate();
        Interfaz.Fecha_Final=jDateChooser2.getDate();
        Interfaz.Leg=jTextField1.getText();
        Interfaz.Apellido=jTextField2.getText();;
        Interfaz.Nombre=jTextField3.getText();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Modificar_Saldos b = new Modificar_Saldos();
        b.setVisible(true);
        this.setVisible(false);
        
        int fila= jTableBD.getSelectedRow();
        if (fila>=0) {
            Modificar_Saldos.jTextField1.setText(jTableBD.getValueAt(fila, 0).toString());
            Modificar_Saldos.jTextField2.setText(jTextField1.getText());
            Modificar_Saldos.jTextField3.setText(jTableBD.getValueAt(fila, 1).toString());
            //TRAER EL CONCEPTO DE LA BASE DE DATOS Y AGREGARLO AL COMBOBOX
            Modificar_Saldos.jComboBox3.addItem(jTableBD.getValueAt(fila, 2).toString().trim());
            //SELECCIONAR COMO PRIMERA OPCION EL CONCEPTO EXPORTADO DE LA BD
            Modificar_Saldos.jComboBox3.setSelectedItem(jTableBD.getValueAt(fila, 2).toString().trim());
            Modificar_Saldos.jTextField5.setText(jTableBD.getValueAt(fila, 3).toString());
            //SELECCIONAR COMO PRIMERA OPCION EL CONCEPTO EXPORTADO DE LA BD
            Modificar_Saldos.jComboBox1.setSelectedItem(jTableBD.getValueAt(fila, 4).toString().trim());
            //SELECCIONAR COMO PRIMERA OPCION EL CONCEPTO EXPORTADO DE LA BD
            Modificar_Saldos.jComboBox2.setSelectedItem(jTableBD.getValueAt(fila, 5).toString().trim());
            Modificar_Saldos.jTextField8.setText(jTableBD.getValueAt(fila, 6).toString());
            Modificar_Saldos.jTextField9.setText(jTableBD.getValueAt(fila, 7).toString());
            
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        //Conectar a la BD  y   actualiza todos sus datos
        Conectar cc= new Conectar();
        Connection cn= cc.conexion();
        
        
        int fila= jTableBD.getSelectedRow();
        
        
        //Eliminar el Dato Seleccionado
        try {
            PreparedStatement pst = cn.prepareStatement("DELETE FROM saldos WHERE Cod='"+jTableBD.getValueAt(fila, 0).toString()+"'"); 
            pst.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Consulta_de_Saldos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jButton2ActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta_de_Saldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta_de_Saldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta_de_Saldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta_de_Saldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta_de_Saldos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBD;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
