/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author tesoreria
 */
public class Imprimir_Resumen extends javax.swing.JFrame {
    //CONEXION A LA BASE DE DATOS
    Conectar cc= new Conectar();
    Connection cn= cc.conexion();

    /**
     * Creates new form Imprimir_Resumen
     */
    public Imprimir_Resumen() {
        initComponents();
        this.setLocationRelativeTo(this);  //CENTRAR VENTANA
    }
    
    void HabilitarBotones(){
        //DESHABILITAR TODOS LOS BOTONES
        if (jTextField3.getText().isEmpty() || jTextField4.getText().isEmpty()){
            jButton3.setEnabled(false);
        } else {
            jButton3.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton_volver_50x50.png"))); // NOI18N
        jButton1.setToolTipText("VOLVER AL MENU PRINCIPAL");
        jButton1.setMaximumSize(new java.awt.Dimension(60, 60));
        jButton1.setMinimumSize(new java.awt.Dimension(60, 60));
        jButton1.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("FECHA INICIAL:");

        jLabel2.setText("FECHA FINAL:");

        jLabel3.setText("DESDE LEG.:");

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });

        jLabel4.setText("HASTA LEG.:");

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton_imprimir_30x30.png"))); // NOI18N
        jButton3.setEnabled(false);
        jButton3.setMaximumSize(new java.awt.Dimension(30, 30));
        jButton3.setMinimumSize(new java.awt.Dimension(30, 30));
        jButton3.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("---");
        jLabel5.setEnabled(false);
        jLabel5.setFocusable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("---");
        jLabel6.setEnabled(false);
        jLabel6.setFocusable(false);
        jLabel6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel6KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //INICIO - PARA COMPLETAR LOS 3 DIGITOS DE LOS CAMPOS LEG
        jTextField3.setText(String.format("%03d",(Integer.parseInt(jTextField3.getText().trim()))));
        jTextField4.setText(String.format("%03d",(Integer.parseInt(jTextField4.getText().trim()))));
        //FIN - PARA COMPLETAR LOS 3 DIGITOS DE LOS CAMPOS LEG
        
        //INICIO - COMPARAR DESDE LEG SEA MENOR O IGUAL, A HASTA LEG
        if ((Integer.parseInt(jTextField3.getText().trim()))>(Integer.parseInt(jTextField4.getText().trim()))){
            JOptionPane.showMessageDialog(null, "DESDE LEG, debe ser menor o igual que, HASTA LEG", "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        //FIN - COMPARAR DESDE LEG SEA MENOR O IGUAL, A HASTA LEG
        //INICIO - COMPARAR FECHA INICIAL SEA MENOR O IGUAL, A FECHA FINAL
        if (jDateChooser1.getDate().after(jDateChooser2.getDate())){
            JOptionPane.showMessageDialog(null, "FECHA INICIAL, debe ser menor o igual que, FECHA FINAL", "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        //FIN - COMPARAR DESDE LEG SEA MENOR O IGUAL, A HASTA LEG
        //INICIO - CUANDO SE LLENO CORRECTAMENTE LOS CAMPOS, SE PROCEDE A IMPRIMIR
        if ((Integer.parseInt(jTextField3.getText().trim()))<=(Integer.parseInt(jTextField4.getText().trim()))&&(jDateChooser1.getDate().before(jDateChooser2.getDate()))){
            Interfaz.Fecha_Inicial=jDateChooser1.getDate();
            Interfaz.Fecha_Final=jDateChooser2.getDate();
            Interfaz.Desde_Leg=jTextField3.getText();
            Interfaz.Hasta_Leg=jTextField4.getText();
            Interfaz.Leg=jTextField3.getText();
            //INICIO - CICLO QUE INICIA EN DESDE_LEG Y TERMINA EN HASTA_LEG
            for(int i=Integer.parseInt(Interfaz.Desde_Leg);i<=Integer.parseInt(Interfaz.Hasta_Leg);i=i+1){
                //INICIO - Buscar APELLIDO Y NOMBRE SEGUN LEG
                String sql = "SELECT * FROM `empleados` WHERE `Leg` LIKE '%"+Interfaz.Leg+"%'";
                String datos[] = new String [2];
                Statement st;
                try{
                    st= cn.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                    while (rs.next()&&(rs.getString(9).equals("S"))){
                        Interfaz.Apellido=(rs.getString(4));
                        Interfaz.Nombre=(rs.getString(5));
                        }
                    }catch (SQLException ex){
                        Logger.getLogger(Imprimir_Resumen.class.getName()).log(Level.SEVERE, null, ex);
                        Interfaz.Apellido="null";
                        }
                //FIN - Buscar APELLIDO Y NOMBRE SEGUN LEG
                //INICIO - SI ENCONTRO EL NUM DE LEG, IMPRIME
                while(Interfaz.Apellido!="null"){
                    DDMYS ddmys = new DDMYS();
                    ddmys.setVisible(true);
                    //MANDAR A IMPRIMIR
                    try {
                        PrinterJob job = PrinterJob.getPrinterJob();
                        job.setPrintable(ddmys);
                        //job.printDialog();
                        job.print();
                        } catch (PrinterException ex) {
                            Logger.getLogger(Imprimir_Resumen.class.getName()).log(Level.SEVERE, null, ex);
                            }
                    //FIN MANDAR A IMPRIMIR
                    ddmys.setVisible(false);
                    Interfaz.Apellido="null";
                    }
                //FIN - SI ENCONTRO EL NUM DE LEG, IMPRIME
                Interfaz.Leg=String.format("%03d",(Integer.parseInt(Interfaz.Leg)+1));
                }
            //FIN - CICLO QUE INICIA EN DESDE_LEG Y TERMINA EN HASTA_LEG
            //INICIO - SALE A PANTALLA PRINCIPAL
            Interfaz interfaz = new Interfaz();
            interfaz.setVisible(true);
            this.setVisible(false);
            //FIN - SALE A PANTALLA PRINCIPAL
            }
        //FIN - CUANDO SE LLENO CORRECTAMENTE LOS CAMPOS, SE PROCEDE A IMPRIMIR
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Interfaz interfaz = new Interfaz();
        interfaz.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:
        //SI jTextField3 ESTA VACIO, BORRA EL jLabel5. Y sino busca al empleado
        if (jTextField3.getText().length() == 0){
            jLabel5.setText("---");
        }else{
            String sql = "SELECT * FROM `empleados` WHERE `Leg` LIKE '%"+jTextField3.getText()+"%'";
            
            String datos[] = new String [2];
            Statement st;
            
            try{
                st= cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()){
                    jLabel5.setText(rs.getString(4)+", "+rs.getString(5));
                    }
                }catch (SQLException ex){
                    Logger.getLogger(Padron_de_Empleados.class.getName()).log(Level.SEVERE, null, ex);
                    }
            }
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
        //PERMITE EL INGRESO UNICAMENTE DE 3 DIGITOS
        if (jTextField3.getText().length()== 3){
            evt.consume();
        } 
        //Permitir solo el ingreso de NUMEROS
        char car = evt.getKeyChar();
        if(car<'0' || car>'9') evt.consume();
        
        HabilitarBotones();
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
        //PERMITE EL INGRESO UNICAMENTE DE 3 DIGITOS
        if (jTextField4.getText().length()== 3){
            evt.consume();
        } 
        //Permitir solo el ingreso de NUMEROS
        char car = evt.getKeyChar();
        if(car<'0' || car>'9') evt.consume();
        
        HabilitarBotones();
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
        //SI jTextField3 ESTA VACIO, BORRA EL jLabel5
        if (jTextField3.getText().length() == 0){
            jLabel5.setText("---");
        }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jLabel6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel6KeyPressed
        // TODO add your handling code here:
        //SI jTextField4 ESTA VACIO, BORRA EL jLabel5
        if (jTextField4.getText().length() == 0){
            jLabel6.setText("---");
        }
    }//GEN-LAST:event_jLabel6KeyPressed

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        // TODO add your handling code here:
        //SI jTextField4 ESTA VACIO, BORRA EL jLabel6. Y sino busca al empleado
        if (jTextField4.getText().length() == 0){
            jLabel6.setText("---");
        }else{
            String sql = "SELECT * FROM `empleados` WHERE `Leg` LIKE '%"+jTextField4.getText()+"%'";
            
            String datos[] = new String [2];
            Statement st;
            
            try{
                st= cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()){
                    jLabel6.setText(rs.getString(4)+", "+rs.getString(5));
                    }
                }catch (SQLException ex){
                    Logger.getLogger(Padron_de_Empleados.class.getName()).log(Level.SEVERE, null, ex);
                    }
            }
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // TODO add your handling code here:
        //SI jTextField4 ESTA VACIO, BORRA EL jLabel6
        if (jTextField4.getText().length() == 0){
            jLabel6.setText("---");
        }
    }//GEN-LAST:event_jTextField4KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Imprimir_Resumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Imprimir_Resumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Imprimir_Resumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Imprimir_Resumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Imprimir_Resumen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
